-- stolen from https://github.com/KevinPalowa/nvim/

require("nauval.options")
require("nauval.autocmds")
require("nauval.keymaps")
require("nauval.plugins")
require("nauval.colorscheme")
require("nauval.cmp")
require("nauval.lsp")
require("nauval.telescope")
require("nauval.presence")
require("nauval.toggleterm")
require("nauval.lualine")
require("nauval.autopairs")
require("nauval.comment")
require("nauval.gitsigns")
require("nauval.nvimtree")
require("nauval.treesitter")
require("nauval.bufferline")
require("nauval.indentline")
require("nauval.trouble")
require("nauval.alpha")
require("nauval.project")
require("nauval.colorizer")
require("nauval.whichkey")
